version: '3.8'

services:
  backend:
    build: ./backend
    container_name: stock-game-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    deploy:
      resources:
        limits:
          memory: 2g

  frontend:
    build: ./frontend
    container_name: stock-game-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
